services:
  db:
    image: postgres:15
    container_name: sprint-shareit
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shareit